export const EMAIL_SCENARIOS = {
  ADD_CUSTOMER: "ADD_CUSTOMER",
  UPDATE_CUSTOMER: "UPDATE_CUSTOMER",
  CANCEL_CUSTOMER: "CANCEL_CUSTOMER",
  UPDATE_SESSION: "UPDATE_SESSION",
  BOOKING_REQUEST: "BOOKING_REQUEST",
  SESSION_PHOTOS_SHARE: "SESSION_PHOTOS_SHARE",
} as const;

export type EmailScenarioType =
  (typeof EMAIL_SCENARIOS)[keyof typeof EMAIL_SCENARIOS];
